### ISSUE TITLE
Remove 'Project' from payload returned by sites.php

### ISSUE THREAD

**Issue by bumbanian** [SPATIAL-Lab/spatial-group-demo#3]
We will be removing the "Project" field from the DB table "Sites", and in preparation should drop this from the sites query output.

**Comment by bumbanian** [comment]
Chonghuan - It looks like Sites.Project is still included in the output from the sites.php query. Can you check this and remove it. Once that's done we can close this issue.

**Comment by HuanUU** [comment]
This is done.
